name: 'happybooking_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'fabric_profile' # Fabric bağlantı profilinizin adı

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"